Repository Hacktoberfest-Nepal/Your-First-PR, pull requests merged in 2020-10, with the labels that each got.

#89 added pr from the demo :)
  pr_from_demo.txt
Labels: Hacktoberfest2020

#88 Added Prabesh Sapkota
  CONTRIBUTORS.md
Labels: hacktoberfest accepted

#95 Update the CONTRIBUTORS.md
  CONTRIBUTORS.md
Labels: hacktoberfest accepted

#91 added the name in contributor
  CONTRIBUTORS.md
Labels: hacktoberfest accepted

#86 added ruzan
  CONTRIBUTORS.md
Labels: hacktoberfest accepted

#102 Update CONTRIBUTORS.md
  CONTRIBUTORS.md
Labels: hacktoberfest-accepted

#100 Updated CONTRIBUTORS.md
  CONTRIBUTORS.md
Labels: hacktoberfest-accepted

#87 updated
  CONTRIBUTORS.md
Labels: hacktoberfest-accepted

#101 Update CONTRIBUTORS.md
  CONTRIBUTORS.md
Labels: hacktoberfest-accepted

#109 Update CONTRIBUTORS.md
  CONTRIBUTORS.md
Labels: hacktoberfest-accepted

#82 Added my contribution in the contributors.md file
  CONTRIBUTORS.md
Labels: hacktoberfest-accepted

#94 Added contribution
  CONTRIBUTORS.md
Labels: hacktoberfest-accepted

#99 Added information in contributor.md file
  CONTRIBUTORS.md
Labels: hacktoberfest-accepted

#106 added contribution
  CONTRIBUTORS.md
Labels: hacktoberfest-accepted

#111 UPDATE: Add my name in contributor list, fix a broken link and align the columns properly
  CONTRIBUTORS.md
Labels: hacktoberfest-accepted
